"""add visit reason  to appointment requests

Revision ID: 9d6880534b48
Revises: 8033d0937d1b
Create Date: 2026-09-20 18:21:58.124424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6880534b48'
down_revision: Union[str, Sequence[str], None] = '8033d0937d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_requests', sa.Column('visit_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_requests', 'visit_reason')
    # ### end Alembic commands ###
