"""add hospital to user roles

Revision ID: a3ad99a188eb
Revises: create_auth_sessions
Create Date: 2026-09-27 13:15:47.157415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3ad99a188eb'
down_revision: Union[str, Sequence[str], None] = 'create_auth_sessions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_user_active'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.add_column('user_roles', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_user_roles_user_id_role_id'), 'user_roles', type_='unique')
    op.create_index(op.f('ix_user_roles_hospital_id'), 'user_roles', ['hospital_id'], unique=False)
    op.create_unique_constraint('uq_user_roles_user_role_hospital', 'user_roles', ['user_id', 'role_id', 'hospital_id'])
    op.create_foreign_key(None, 'user_roles', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint('uq_user_roles_user_role_hospital', 'user_roles', type_='unique')
    op.drop_index(op.f('ix_user_roles_hospital_id'), table_name='user_roles')
    op.create_unique_constraint(op.f('uq_user_roles_user_id_role_id'), 'user_roles', ['user_id', 'role_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_roles', 'hospital_id')
    op.create_table('auth_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('refresh_token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('replaced_by_session_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('device_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('auth_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_sessions_pkey')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_auth_sessions_refresh_token_hash'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('session_id', name=op.f('uq_auth_sessions_session_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_active'), 'auth_sessions', ['user_id', 'is_revoked'], unique=False)
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    # ### end Alembic commands ###
