"""add appointment response fields

Revision ID: ad29b283d485
Revises: 7a67b0e84ecc
Create Date: 2026-09-23 19:23:05.993273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad29b283d485'
down_revision: Union[str, Sequence[str], None] = '7a67b0e84ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_requests', sa.Column('proposed_start_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointment_requests', sa.Column('proposal_message', sa.Text(), nullable=True))
    op.add_column('appointment_requests', sa.Column('decline_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_requests', 'decline_reason')
    op.drop_column('appointment_requests', 'proposal_message')
    op.drop_column('appointment_requests', 'proposed_start_at')
    # ### end Alembic commands ###
